### ISSUE TITLE
Weight Calculation

### ISSUE THREAD

**Issue by ulteriorlife** [trobey/commerce_usps#4]
When determining the weight of an order the quantity of each item isn't being taken into account.

ie: Customer increases the quantity of an item to 10 that weighs 1 lb each, should send 10lbs to usps only sends 1lb.

**Comment by trobey** [comment]
Which version of Commerce Shipping are you using?

**Comment by trobey** [comment]
It does appear that the quantity was missing from the weight calculation.  Please review.

**Comment by ulteriorlife** [comment]
Looks good and is now working as intended. Thank You!
